import { ITransaction } from "../interface/Transaction";

export const mockTransactions: ITransaction[] = [
    {
        id: 1,
        description: "Di chuyển",
        amount: "-50.000 VND",
        category: "Di chuyển",
        date: "20/03/2025",
        time: "09:00",
        paymentMethod: "Tiền mặt",
        location: "Hà Nội",
        image: "https://th.bing.com/th/id/OIP.OkKi7MagZ2MS57OrhjQ7hQAAAA?rs=1&pid=ImgDetMain",
        notes: ""
    },
    {
        id: 11,
        description: "Di chuyển",
        amount: "-50.000 VND",
        category: "Di chuyển",
        date: "20/03/2025",
        paymentMethod: "Tiền mặt",
        location: "Hà Nội",
        image: "https://th.bing.com/th/id/OIP.bi66zoR_BWkIErHOvc3GuAHaEl?rs=1&pid=ImgDetMain",
        notes: "",
        time: "10:00",
    },
    {
        id: 2,
        description: "Tiền điện tháng 3",
        amount: "-300.000 VND",
        category: "Tiền điện",
        date: "20/03/2025",
        time: "10:00",
        paymentMethod: "Chuyển khoản",
        location: "Hà Nội",
        image: "",
        notes: "Hoá đơn điện tháng 3/2025"
    },
    {
        id: 3,
        description: "Tiền nước",
        amount: "-100.000 VND",
        category: "Tiền nước",
        date: "20/03/2025",
        time: "10:00",
        paymentMethod: "Tiền mặt",
        location: "Hà Nội",
        image: "",
        notes: ""
    },
    {
        id: 4,
        description: "Thu nhập khác",
        amount: "1.000.000 VND",
        category: "Thu nhập",
        date: "20/03/2025",
        time: "10:00",
        paymentMethod: "Chuyển khoản",
        location: "Hà Nội",
        notes: "Tiền bán đồ cũ",
        image: "",
    },
    {
        id: 5,
        description: "Ăn uống",
        amount: "-200.000 VND",
        category: "Ăn uống",
        date: "19/03/2025",
        time: "10:00",
        paymentMethod: "Tiền mặt",
        location: "Hà Nội",
        image: "",
        notes: "Ăn tối tại nhà hàng"
    },
    {
        id: 6,
        description: "Mua sắm",
        amount: "-500.000 VND",
        category: "Mua sắm",
        date: "18/03/2025",
        time: "10:00",
        paymentMethod: "Chuyển khoản",
        location: "Hà Nội",
        image: "",
        notes: "Mua quần áo"
    },
    {
        id: 7,
        description: "Tiền thuê nhà",
        amount: "-3.000.000 VND",
        category: "Thuê nhà",
        date: "17/03/2025",
        time: "10:00",
        paymentMethod: "Chuyển khoản",
        location: "Hà Nội",
        image: "",
        notes: "Tiền thuê nhà tháng 3/2025"
    },
    {
        id: 8,
        description: "Tiền lương tháng 3",
        amount: "15.000.000 VND",
        category: "Thu nhập",
        date: "16/03/2025",
        time: "10:00",
        paymentMethod: "Chuyển khoản",
        location: "Hà Nội",
        image: "",
        notes: "Lương công ty"
    },
    {
        id: 9,
        description: "Xăng xe",
        amount: "-100.000 VND",
        category: "Di chuyển",
        date: "15/03/2025",
        time: "10:00",
        paymentMethod: "Tiền mặt",
        location: "Hà Nội",
        image: "",
        notes: "Đổ xăng xe máy"
    },
    {
        id: 10,
        description: "Internet tháng 3",
        amount: "-200.000 VND",
        category: "Internet",
        date: "14/03/2025",
        time: "10:00",
        paymentMethod: "Chuyển khoản",
        location: "Hà Nội",
        image: "",
        notes: "Thanh toán cước internet"
    },
    {
        id: 12,
        description: "Internet mới nhất",
        amount: "-200.000 VND",
        category: "Internet",
        date: "23/03/2025",
        time: "10:00",
        paymentMethod: "Chuyển khoản",
        location: "Hà Nội",
        image: "",
        notes: "Thanh toán cước internet"
    }
];
