import { ITransaction, TransactionType, PayMethod } from "../interface/Transaction";

export const transactions: ITransaction[] = [
    {
        id: "21",
        userId: "12",
        description: "Di chuyển",
        amount: 50000,
        category: "Di chuyển",
        date: "20/03/2025",
        time: "09:00",
        paymentMethod: PayMethod.CASH,
        location: "Hà Nội",
        image: "https://th.bing.com/th/id/OIP.OkKi7MagZ2MS57OrhjQ7hQAAAA?rs=1&pid=ImgDetMain",
        note: "",
        type: TransactionType.EXPENSE
    },
    {
        id: "11",
        userId: "12",
        description: "Di chuyển",
        amount: 50000,
        category: "Di chuyển",
        date: "20/03/2025",
        paymentMethod: PayMethod.CASH,
        location: "Hà Nội",
        image: "https://th.bing.com/th/id/OIP.bi66zoR_BWkIErHOvc3GuAHaEl?rs=1&pid=ImgDetMain",
        note: "",
        time: "10:00",
        type: TransactionType.EXPENSE
    },
    {
        id: "2",
        userId: "12",
        description: "Tiền điện tháng 3",
        amount: 300000,
        category: "Tiền điện",
        date: "20/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.BANK_TRANSFER,
        location: "Hà Nội",
        image: "",
        note: "Hoá đơn điện tháng 3/2025",
        type: TransactionType.EXPENSE
    },
    {
        id: "3",
        userId: "12",
        description: "Tiền nước",
        amount: 100000,
        category: "Tiền nước",
        date: "20/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.CASH,
        location: "Hà Nội",
        image: "",
        note: "",
        type: TransactionType.EXPENSE
    },
    {
        id: "4",
        userId: "12",
        description: "Thu nhập khác",
        amount: 1000000,
        category: "Khác",
        date: "20/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.BANK_TRANSFER,
        location: "Hà Nội",
        note: "Tiền bán đồ cũ",
        image: "",
        type: TransactionType.INCOME
    },
    {
        id: "5",
        userId: "12",
        description: "Ăn uống",
        amount: 200000,
        category: "Ăn uống",
        date: "19/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.CASH,
        location: "Hà Nội",
        image: "",
        note: "Ăn tối tại nhà hàng",
        type: TransactionType.EXPENSE
    },
    {
        id: "6",
        userId: "12",
        description: "Mua sắm",
        amount: 500000,
        category: "Mua sắm",
        date: "18/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.BANK_TRANSFER,
        location: "Hà Nội",
        image: "",
        note: "Mua quần áo",
        type: TransactionType.EXPENSE
    },
    {
        id: "7",
        userId: "12",
        description: "Tiền thuê nhà",
        amount: 3000000,
        category: "Thuê nhà",
        date: "17/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.CASH,
        location: "Hà Nội",
        image: "",
        note: "Tiền thuê nhà tháng 3/2025",
        type: TransactionType.EXPENSE
    },
    {
        id: "8",
        userId: "12",
        description: "Tiền lương tháng 3",
        amount: 15000000,
        category: "Lương",
        date: "16/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.BANK_TRANSFER,
        location: "Hà Nội",
        image: "",
        note: "Lương công ty",
        type: TransactionType.INCOME
    },
    {
        id: "9",
        userId: "12",
        description: "Xăng xe",
        amount: 100000,
        category: "Di chuyển",
        date: "15/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.CASH,
        location: "Hà Nội",
        image: "",
        note: "Đổ xăng xe máy",
        type: TransactionType.EXPENSE
    },
    {
        id: "10",
        userId: "12",
        description: "Internet tháng 3",
        amount: 200000,
        category: "Internet",
        date: "14/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.BANK_TRANSFER,
        location: "Hà Nội",
        image: "",
        note: "Thanh toán cước internet",
        type: TransactionType.EXPENSE
    },
    {
        id: "12",
        userId: "12",
        description: "Internet mới nhất",
        amount: 200000,
        category: "Internet",
        date: "23/03/2025",
        time: "10:00",
        paymentMethod: PayMethod.BANK_TRANSFER,
        location: "Hà Nội",
        image: "",
        note: "Thanh toán cước internet",
        type: TransactionType.EXPENSE
    },
    {
        id: "13",
        userId: "12",
        description: "Đầu tư trading",
        amount: 3000000,
        category: "Đầu tư",
        date: "20/02/2025",
        time: "10:00",
        paymentMethod: PayMethod.CASH,
        location: "Hà Nội",
        image: "",
        note: "",
        type: TransactionType.INCOME
    },
    {
        id: "14",
        userId: "12",
        description: "Đầu tư trading",
        amount: 3000000,
        category: "Đầu tư",
        date: "30/04/2025",
        time: "10:00",
        paymentMethod: PayMethod.CASH,
        location: "Hà Nội",
        image: "",
        note: "",
        type: TransactionType.INCOME
    }
];